### ISSUE TITLE
js

### ISSUE THREAD

**Issue by Frolikow** [OlyaSkoroded/ui-kit#12]
объясни плиз вот эту конструкцию 
![image](https://user-images.githubusercontent.com/25764783/64919666-b1a79080-d7d7-11e9-962c-5a849009ee09.png)
в частности два восклицательных знака. почему именно так решено было сделать

**Comment by OlyaSkoroded** [comment]
Это линтер мне посоветовал😵

**Comment by OlyaSkoroded** [comment]
Блин я там изначально ненужный тернарник написала, линтер ругался, предложил пофиксить и сделал вот это, а я даже внимания не обратила, поторопилась
