### ISSUE TITLE
ui kit

### ISSUE THREAD

**Issue by Frolikow** [OlyaSkoroded/ui-kit#2]
1) STANDARD BUTTONS
+ кнопки имеют интерактивность, не только рипл эффект. Например в первой строке кнопки идут в момент нажатия на них, во второй строке - дефолтный вид кнопок, а последний ряд это те же кнопки но с "инверсией цвета". И сразу обрати внимание на то что в последнем ряду, рипл тоже должен быть с измененным цветом.
2) ARROW BUTTONS
+ примерно то же самое, что и выше. Слева и справа кнопки просто с инверсией цвета и при ховере меняются. По середине пара кнопок - это "отключенные" кнопки, т.е. на них при ховере даже курсор не должен меняться.
3)FORM ELEMENTS 
+ немного сползи "пипки" у подзказок
![image](https://user-images.githubusercontent.com/25764783/63783242-dc0fd780-c916-11e9-9fd6-005c74c94988.png)
4) TOGGLES / TICK BOXES
+ при увеличении масштаба страницы, кривятся элементы: 
![image](https://user-images.githubusercontent.com/25764783/63783370-1c6f5580-c917-11e9-81ba-2812a74dbb1c.png)
5) DROP DOWN
 + при клике по стрелочке, список не открывается. 
 + у списка есть конкретные стили в макете. Посмотри в psd в слоях, он там скрыт по дефолту
6) USER PROFILE
 + опять что-то с "пипками") 
![image](https://user-images.githubusercontent.com/25764783/63783597-7708b180-c917-11e9-8784-b09006e7a09f.png)
7) CALENDAR / MESSAGING
 + нижний край элементов расходится
![image](https://user-images.githubusercontent.com/25764783/63783690-9ef81500-c917-11e9-88e0-7ea4f5e84fbc.png)

Пока основное что в глаза бросилось, после правок буду сравнивать с perfectPixel

**Comment by OlyaSkoroded** [comment]
Не знаю как с календарем поступить, там в плагине по умолчанию рисуется больше рядов чем нужно, а в код плагина вроде как нельзя залезать😶

**Comment by Frolikow** [comment]
1. Кнопки правильные.
2. Кнопки-стрелки правильные, но при ховере, уголок внутри кнопок немного прыгает из стороны в сторону
3. Хорошо
4. Хорошо
5. Выпадающий список не совсем по макету:
![image](https://user-images.githubusercontent.com/25764783/64145009-317d4480-ce41-11e9-855f-651328300645.png)
![image](https://user-images.githubusercontent.com/25764783/64145024-37732580-ce41-11e9-90c7-a800a11711e1.png)
Нужно текст заменить на соответствующий,  между блоком и списком не такое явное разделение .
6. Хорошо
7. На счет календаря. В код плагина лезть - да, плохая затея. Но ведь сам календарь состоит из html элементов, которым можно задать стили) чему-то размер заменить, или шрифт, или вообще что-то скрыть) кастомизацию никто не запрещает делать)

**Comment by OlyaSkoroded** [comment]
![Безымянный](https://user-images.githubusercontent.com/43029118/64613473-67ea2f00-d400-11e9-917f-712074d677b9.png)
![календарь](https://user-images.githubusercontent.com/43029118/64613482-6a4c8900-d400-11e9-8e08-efc6362788ed.png)
С календарем только так получилось сделать, лишние ряды не рисуются, но перфект пиксель только если по следующему месяцу смотреть, т.к. там количество рядов с макетом совпадает. Задала фиксированную высоту обертке, чтобы верстка не прыгала при переключении месяцев
