### ISSUE TITLE
Сломалась страница регистрации

### ISSUE THREAD

**Issue by Znack** [OlyaSkoroded/ui-kit#20]
На странице https://olyaskoroded.github.io/ui-kit/dist/checkIn.html сломалась верстка :(

![image](https://user-images.githubusercontent.com/2928964/69897034-c926fc00-1378-11ea-9cad-ab3cfa43dc0d.png)

Или это и должно так быть? :)

**Comment by OlyaSkoroded** [comment]
Исправила)
