### ISSUE TITLE
Правки по замечаниям к первому проекту

### ISSUE THREAD

**Issue by Nelliza** [OlyaSkoroded/ui-kit#21]
Внеси пожалуйста правки в соответствии с замечаниями к первому проекту, чтобы сэкономить нам обеим время на ревью )

**Comment by OlyaSkoroded** [comment]
Подскажи пожалуйста, как эту гадость исправить, нужный лоадер ведь есть
![warnings](https://user-images.githubusercontent.com/43029118/72242223-78631e00-361b-11ea-9c10-923105c9da3a.png)

**Comment by Nelliza** [comment]
> Подскажи пожалуйста, как эту гадость исправить, нужный лоадер ведь есть

Вопрос решен в личной переписке
