### ISSUE TITLE
Хардкод

### ISSUE THREAD

**Issue by Nelliza** [OlyaSkoroded/ui-kit#29]
У тебя сейчас в ряде компонентов (**drop-down**, **messaging** и др., нужно посмотреть везде) некоторые значения жестко вшиты без возможности их изменять через аргументы. Что, если тебе нужно будет подключить несколько одних и тех же компонентов с разными значениями?
Нужно стараться по-максимуму добавлять возможность кастомизации компонентов через аргументы.

Для миксинов кнопок, подключаемых внутри других миксинов, опции также следует прокидывать сверху вниз, т.е. от внешнего миксина ко внутреннему

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/73554699-45af8700-445d-11ea-857b-8296fb51cad8.png)
А почему здесь заменила `each` на цикл `for`? )

**Comment by OlyaSkoroded** [comment]
Затупила по невнимательности(

**Comment by Nelliza** [comment]
Думаю, `alt` у изображений тоже не следует хардкодить:
https://github.com/OlyaSkoroded/ui-kit/blob/75a95c36290fdcf707fe7d4e9eb10cc938e8987b/src/blocks/events/events.pug#L17
https://github.com/OlyaSkoroded/ui-kit/blob/75a95c36290fdcf707fe7d4e9eb10cc938e8987b/src/blocks/avatar/avatar.pug#L6
https://github.com/OlyaSkoroded/ui-kit/blob/75a95c36290fdcf707fe7d4e9eb10cc938e8987b/src/blocks/messaging/messaging.pug#L18
https://github.com/OlyaSkoroded/ui-kit/blob/75a95c36290fdcf707fe7d4e9eb10cc938e8987b/src/blocks/news/news.pug#L12
https://github.com/OlyaSkoroded/ui-kit/blob/75a95c36290fdcf707fe7d4e9eb10cc938e8987b/src/blocks/user-profile/user-profile.pug#L3

**Comment by Nelliza** [comment]
Думаю, `alt` у изображений тоже не следует хардкодить:
https://github.com/OlyaSkoroded/ui-kit/blob/75a95c36290fdcf707fe7d4e9eb10cc938e8987b/src/blocks/events/events.pug#L17
https://github.com/OlyaSkoroded/ui-kit/blob/75a95c36290fdcf707fe7d4e9eb10cc938e8987b/src/blocks/avatar/avatar.pug#L6
https://github.com/OlyaSkoroded/ui-kit/blob/75a95c36290fdcf707fe7d4e9eb10cc938e8987b/src/blocks/messaging/messaging.pug#L18
https://github.com/OlyaSkoroded/ui-kit/blob/75a95c36290fdcf707fe7d4e9eb10cc938e8987b/src/blocks/news/news.pug#L12
https://github.com/OlyaSkoroded/ui-kit/blob/75a95c36290fdcf707fe7d4e9eb10cc938e8987b/src/blocks/user-profile/user-profile.pug#L3
