### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by Frolikow** [OlyaSkoroded/ui-kit#3]
Надо пройтись по всему проекту и поправить ошибки eslint'а

**Comment by Frolikow** [comment]
Во многих местах еще красные подчеркивания встречаются
![image](https://user-images.githubusercontent.com/25764783/64145925-17ddfc00-ce45-11e9-92be-86aa2c73ce6c.png)

**Comment by Frolikow** [comment]
Странно, сейчас тоже пропали все места связанные с этой ошибкой.

1) На счет ymaps, давай для простоты отключим это правило в данном js-файле. 
2) На счет ошибки при вызове конструктора класса(это в разных местах есть). 
+ Там во-первых у тебя анонимная функция. Просто замени ее на стрелочную.
+ Во-вторых ошибка eslint(no-new). В данном случае лучше прочитать об этой ошибке тут: [доки еслинта](https://eslint.org/docs/rules/no-new).
Вообще когда появляется ошибка линтера, самый лучший вариант - заходить в гугл и смотреть что это за ошибка. Обычно хватает оф доков, но если там не ясно, но точно найдется пояснение от кого-нибудь))

**Comment by OlyaSkoroded** [comment]
Спасибо большое, что объяснил))

**Comment by Frolikow** [comment]
В данном случае просто отключить правило линтера не лучший вариант
![image](https://user-images.githubusercontent.com/25764783/65128132-10ad1580-da23-11e9-8f17-df7dbcecb02e.png)
всегда нужно стараться исправить, и в крайних случаях выключать.
Здесь же я скинул доку не зря) там почти в самом начале описано как пофиксить чтобы линтер не урчал)
![image](https://user-images.githubusercontent.com/25764783/65128228-44883b00-da23-11e9-9b4f-392bb8045f3a.png)
