### ISSUE TITLE
Календарь

### ISSUE THREAD

**Issue by Nelliza** [OlyaSkoroded/ui-kit#30]
Сейчас у тебя при переходе с одного месяца на другой календарь меняет размер из-за разного количества недель. Исправь пожалуйста, чтобы высота календаря не зависела от выбранного месяца

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/73552704-c8cede00-4459-11ea-81ea-9fe9516b56dc.png)
Почему-то сегодняшний день стал голубого цвета )

**Comment by OlyaSkoroded** [comment]
> Сейчас у тебя при переходе с одного месяца на другой календарь меняет размер из-за разного количества недель. Исправь пожалуйста, чтобы высота календаря не зависела от выбранного месяца

Не понимаю, как решить проблему, не затрагивая при этом код самого плагина

**Comment by Nelliza** [comment]
> Не понимаю, как решить проблему, не затрагивая при этом код самого плагина

Как вариант, можно задать высоту для контейнера с ячейками, а для самих ячеек заменить жестко заданную высоту на `height: auto`

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/73860903-568d3d80-484d-11ea-97b3-328b4ad0a5fa.gif)
Поправь плиз еще стили при ховере )
