### ISSUE TITLE
PerfectPixel

### ISSUE THREAD

**Issue by Nelliza** [OlyaSkoroded/ui-kit#35]
Cкинь пожалуйста сюда скрин макета с наложенным PerfectPixel (желательно в инверсии) и с открытым окошком настроек

**Comment by OlyaSkoroded** [comment]
Было вот так
![pxp1B](https://user-images.githubusercontent.com/43029118/74237000-57fab200-4cf4-11ea-9a44-92060ef3d0c7.jpg)
![pxp2B](https://user-images.githubusercontent.com/43029118/74237003-5c26cf80-4cf4-11ea-838e-176c31cfe89f.jpg)
![pxp3B](https://user-images.githubusercontent.com/43029118/74237007-6052ed00-4cf4-11ea-9c9c-9df5eb4df572.jpg)
![pxp4B](https://user-images.githubusercontent.com/43029118/74237014-6648ce00-4cf4-11ea-9d7e-83772ec792ac.jpg)

**Comment by OlyaSkoroded** [comment]
Я чуть поправила 
![pxp1A](https://user-images.githubusercontent.com/43029118/74237545-a0ff3600-4cf5-11ea-8f03-70011ad3f761.jpg)
![pxp3A](https://user-images.githubusercontent.com/43029118/74237631-cee47a80-4cf5-11ea-839d-688528ae8bb7.jpg)
![pxp4A](https://user-images.githubusercontent.com/43029118/74237660-dc9a0000-4cf5-11ea-986e-83d8c8094c66.jpg)
![pxp2A](https://user-images.githubusercontent.com/43029118/74237681-ed4a7600-4cf5-11ea-9c4d-7bfd60743d11.jpg)

**Comment by Nelliza** [comment]
**Tick boxes** сильно отклонились от нормы, их поправь плиз, остальное не сильно критично, думаю )
