### ISSUE TITLE
Добавить dist в гитигнор

### ISSUE THREAD

**Issue by Nelliza** [OlyaSkoroded/ui-kit#37]

**Comment by OlyaSkoroded** [comment]
Есть)

**Comment by Nelliza** [comment]
Тут моя вина, подробно не расписала этот момент ) Ты сейчас заигнорила папку сборки, но при этом тебе же нужно как-то заливать актуальное состояние на Github Pages, можешь использовать для этой цели плагин `gh-pages` как вариант (он у тебя будет `devDependencies`, кстати)

Также тебе нужно удалить эту папку из кэша репозитория, т.к. сейчас она еще присутствует в корне проекта
