### ISSUE TITLE
Stylus

### ISSUE THREAD

**Issue by Frolikow** [OlyaSkoroded/ui-kit#4]
Не совсем понятно, почему иногда в стилях 1 апмерсанд а иногда 2
![image](https://user-images.githubusercontent.com/25764783/63790766-33687480-c924-11e9-89a4-3fe07ef53177.png)

**Comment by OlyaSkoroded** [comment]
Исправила в ишью #2

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/64919461-2deca480-d7d5-11e9-90fe-be8cdbadce26.png)
здесь у тебя много раз дублируется имя блока. stylus предлагает удобные способы избегать этого) [доки стайлуса](http://stylus-lang.com/docs/selectors.html)
