### ISSUE TITLE
Стилизация в js

### ISSUE THREAD

**Issue by Nelliza** [OlyaSkoroded/ui-kit#44]
![1](https://user-images.githubusercontent.com/19621113/75048834-3bbbf980-54da-11ea-9143-d07ff6682abf.png)

Раздел "Хорошие практики" js-стандартов:

22. **Все изменения в стилях, которые можно сделать через переключение классов у элемента, надо делать через добавление/удаление классов, а не простановку стилей у DOM-элементов. Так, например, можно переключать видимость элемента. Однако для непрерывно изменяющихся численных значений так сделать уже не получится, как например при изменении свойства `top` при скролле страницы, поэтому тут придётся все-таки проставлять напрямую у элемента значение в css-свойстве.**;
    > Это не только увеличит производительность (потому что за раз вы примените сразу все стили от нового класса), но и поможет потом переписать стили из css нормальным способом, потому что иначе стили будут инлайновые и из css их нельзя будет переопределить, кроме как через `!important`.

По-моему, это как раз твой случай ) Посмотри пожалуйста по всему проекту, где можно обойтись классами вместо вызова `css()`

**Comment by OlyaSkoroded** [comment]
Пока исправляла это замечание в Toggle, поняла, что там в принципе излишне js использовать и переписала все на css, надеюсь, так можно было

**Comment by Nelliza** [comment]
> Пока исправляла это замечание в Toggle, поняла, что там в принципе излишне js использовать и переписала все на css, надеюсь, так можно было

Да, так даже предпочтительнее )
